# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: uispec

before:
  hooks:
    - go mod tidy

builds:
  - id: uispec
    main: ./cmd/uispec
    binary: uispec
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.CommitDate}}
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=zig cc -target x86_64-macos-none{{end}}
          {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-macos-none{{end}}
        {{- else if eq .Os "linux" }}
          {{- if eq .Arch "amd64"}}CC=zig cc -target x86_64-linux-musl{{end}}
          {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-linux-musl{{end}}
        {{- else if eq .Os "windows" }}
          {{- if eq .Arch "amd64"}}CC=zig cc -target x86_64-windows-gnu{{end}}
          {{- if eq .Arch "arm64"}}CC=zig cc -target aarch64-windows-gnu{{end}}
        {{- end }}
      - >-
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CXX=zig c++ -target x86_64-macos-none{{end}}
          {{- if eq .Arch "arm64"}}CXX=zig c++ -target aarch64-macos-none{{end}}
        {{- else if eq .Os "linux" }}
          {{- if eq .Arch "amd64"}}CXX=zig c++ -target x86_64-linux-musl{{end}}
          {{- if eq .Arch "arm64"}}CXX=zig c++ -target aarch64-linux-musl{{end}}
        {{- else if eq .Os "windows" }}
          {{- if eq .Arch "amd64"}}CXX=zig c++ -target x86_64-windows-gnu{{end}}
          {{- if eq .Arch "arm64"}}CXX=zig c++ -target aarch64-windows-gnu{{end}}
        {{- end }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: uispec
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*
      - catalogs/**/*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: gnana997
    name: uispec
  prerelease: auto
  name_template: "UISpec v{{.Version}}"

brews:
  - repository:
      owner: gnana997
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/gnana997/uispec"
    description: "Give AI agents deep knowledge of your component library"
    license: "MIT"
    install: |
      bin.install "uispec"
    test: |
      system "#{bin}/uispec", "version"
    commit_author:
      name: "GoReleaser Bot"
      email: "goreleaser@users.noreply.github.com"
    skip_upload: auto
