package main

import (
	"fmt"
	"os"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/gnana997/uispec/catalogs"
)

func newInitCmd() *cobra.Command {
	var preset, catalogFlag string
	var force, skipSetup, yes bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Initialize a new uispec project",
		Long:  "Sets up a .uispec directory with a catalog and config file. Optionally configures AI agent integrations.",
		Annotations: map[string]string{"group": "core"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Interactive mode: if no flags set and TTY, prompt user.
			if !yes && outCfg.IsTTY && catalogFlag == "" && !cmd.Flags().Changed("preset") {
				err := runInteractiveInit(&preset, &catalogFlag)
				if err != nil {
					// If user cancelled, just return.
					if err.Error() == "user aborted" {
						return nil
					}
					return err
				}
			}

			if catalogFlag != "" {
				preset = "" // explicit --catalog overrides the default preset
			}
			if preset != "" && preset != "shadcn" && preset != "radix" {
				return fmt.Errorf("unknown preset %q (available: shadcn, radix)", preset)
			}

			// Create .uispec/catalogs/ directory.
			if err := os.MkdirAll(".uispec/catalogs", 0755); err != nil {
				return fmt.Errorf("error creating .uispec/: %w", err)
			}

			// Guard against overwrite.
			if !force {
				if _, err := os.Stat(".uispec/config.yaml"); err == nil {
					return fmt.Errorf(".uispec/config.yaml already exists — use --force to overwrite")
				}
			}

			catalogPath := catalogFlag

			// Write preset catalog.
			switch preset {
			case "shadcn":
				dest := ".uispec/catalogs/shadcn.json"
				if err := os.WriteFile(dest, catalogs.ShadcnJSON, 0644); err != nil {
					return fmt.Errorf("error writing preset catalog: %w", err)
				}
				catalogPath = dest
				if outCfg.Verbosity != VerbQuiet {
					fmt.Printf("wrote %s (%d bytes)\n", dest, len(catalogs.ShadcnJSON))
				}
			case "radix":
				// Radix preset: user needs to pull the catalog.
				if outCfg.Verbosity != VerbQuiet {
					fmt.Println("Radix preset selected. Run 'uispec catalog pull radix' to download the catalog.")
				}
			}

			// Build and write config YAML.
			cfg := ProjectConfig{
				Version:     "1",
				Framework:   "react",
				CatalogPath: catalogPath,
			}
			body, err := yaml.Marshal(cfg)
			if err != nil {
				return fmt.Errorf("error marshaling config: %w", err)
			}
			header := "# UISpec project configuration\n# Generated by: uispec init\n"
			if err := os.WriteFile(".uispec/config.yaml", append([]byte(header), body...), 0644); err != nil {
				return fmt.Errorf("error writing config: %w", err)
			}

			if outCfg.Verbosity != VerbQuiet {
				fmt.Printf("\n  %s Project initialized\n", styleSuccess("✓"))
				fmt.Printf("    Wrote %s\n", styleBold(".uispec/config.yaml"))

				renderNextSteps([]NextStep{
					{"uispec scan src/", "Scan your components"},
					{"uispec serve", "Start MCP server"},
				})
				fmt.Println()
			}

			// Run agent setup unless --skip-setup was given.
			if !skipSetup && !yes {
				executeSetup(os.Stdin, os.Stdout, setupOptions{})
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&preset, "preset", "shadcn", "Preset catalog (shadcn, radix)")
	cmd.Flags().StringVar(&catalogFlag, "catalog", "", "Use a custom catalog path instead of preset")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite existing config")
	cmd.Flags().BoolVar(&skipSetup, "skip-setup", false, "Skip AI agent configuration")
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "Non-interactive mode (use defaults)")

	return cmd
}

// runInteractiveInit runs the huh form for guided initialization.
func runInteractiveInit(preset *string, catalogPath *string) error {
	var choice string
	var customPath string

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("Component library").
				Description("Choose a preset or bring your own catalog").
				Options(
					huh.NewOption("shadcn/ui", "shadcn"),
					huh.NewOption("Radix UI", "radix"),
					huh.NewOption("Custom catalog path", "custom"),
				).
				Value(&choice),
		),
		huh.NewGroup(
			huh.NewInput().
				Title("Catalog path").
				Description("Path to your custom catalog JSON file").
				Placeholder("./path/to/catalog.json").
				Value(&customPath),
		).WithHideFunc(func() bool { return choice != "custom" }),
	)

	if err := form.Run(); err != nil {
		return err
	}

	if choice == "custom" {
		*preset = ""
		*catalogPath = customPath
	} else {
		*preset = choice
	}
	return nil
}
